### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by ErinHahn** [harmancilab/EpiSAFARI#1]
When running spline fitting, I'm experiencing a core dump with some particularly large files (three 25GB BAM files). I'm running it on the files both pooled and unpooled. When run unpooled, spline fitting completes without any issues when I allocate 8 cpus and 20GB Memory.

I've set the parameters as outlined in the documentation:
```
n_spline_coeffs=10
spline_order=5
max_max_err=5
max_avg_err=3
l_win=1000
l_step_win=1000
sparse_data=0
l_post_filter=50
brkpt_type=1
min_POI_distance_in_bps=50

EpiSAFARI -bspline_encode -signal_dir ${PROC_READS_DIR} \
	-n_spline_coeff ${n_spline_coeffs} \
	-bspline_order ${spline_order} \
	-max_max_err ${max_max_err} \
	-max_avg_err ${max_avg_err} \
	-l_win ${l_win} \
	-min_POI_distance ${min_POI_distance_in_bps} \
	-sparse_profile ${sparse_data} \
	-brkpts_type ${brkpt_type} \
	-l_step_win ${l_step_win} \
	-l_post_filt_win ${l_post_filter}

```

When I pool the files, I get:

```
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
/cm/local/apps/slurm/var/spool/job45429159/slurm_script: line 69: 14014 Aborted                 (core dumped) 
```

I've tried increasing the allocated Memory up to 500GB and it continues to fail. Also, unlike the runs on the smaller BAM files, it doesn't seem to be using the 8 cpus. 

Are my files simply too big?

**Comment by harmancilab** [comment]
Hi @ErinHahn , thank you much for your interest and your message. Based on what you are observing, there may be too many points-of-interest in some windows, but even that is a little not very . You can change the ordering of the chromosomes and see if any one of the chromosomes are causing the problems. For this, you can change the order of chromosomes by changing the lines in '${PROC_READS_DIR}/chr_ids.txt' file; these are the chromosome id's that episafari processes in the order it sees them in the file. 

If you wish, I can take a look at the processed data, for this i would need only the gzipped processed reads file (from under ${PROC_READS_DIR}) for the chromosome that causes the issue.

**Comment by ErinHahn** [comment]
Hi @harmancilab. Thanks for the response. I subsampled my BAMs to reduce their size and that allowed the spline fitting to complete. For now, I'm happy with that as the pooled samples still amount to roughly 60X coverage of my genome.

**Comment by harmancilab** [comment]
Great, i will then close this issue. Please let me know if there is anything i can help with.
